server:
  port: 9000

spring:
  profiles:
    active: @spring.active@
  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path=/swagger-ui.html