spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nabootauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
#    password: mysql

webserver:
  url: http://localhost:8080

socketserver:
  url: http://localhost:9010