spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3390/nabootauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: mysql

cors:
  front-app-url: http://app:80