spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3306/nabootauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: nabootauth

webserver:
  url: http://web-service:8080

socketserver:
  url: http://web-socket:9010